version: "3.3"
services:

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bspauto
      POSTGRES_USER: bspauto
      POSTGRES_PASSWORD: bspauto
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bspauto"]
      interval: 5s
      timeout: 2s
      retries: 10

  db_test:
    image: postgres:15
    environment:
      POSTGRES_DB: bspauto_test
      POSTGRES_USER: bspauto_test
      POSTGRES_PASSWORD: bspauto_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bspauto_test"]
      interval: 5s
      timeout: 2s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bspauto.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "5050:80"
